"""Local annotation behavior analytics contracts and utilities."""

from .catalog import EVENT_CATALOG, EventDefinition, sanitize_payload
from .action_catalog import (
    ACTION_CATALOG,
    ACTION_CATALOG_VERSION,
    ActionCatalogEntry,
    action_catalog_to_dict,
    validate_action_catalog,
)
from .activity import ActivityTracker, ActivityTransition
from .action_span import (
    ActionSpanTracker,
    CompletedAction,
    compare_action_summaries,
)
from .burst import BurstAggregator, CompletedBurst
from .clock import ClockReading, SystemClock
from .feature_state import (
    DEFAULT_FEATURE_KEYS,
    FeatureDefinition,
    FeatureRegistry,
    FeatureState,
    FeatureStateTracker,
)
from .identifiers import IdentifierHasher, new_session_id
from .analysis import (
    AnalysisFilter,
    ReadQuality,
    calculate_statistics,
    read_events,
)
from .pipeline import (
    DualRangeSelection,
    RangeSelection,
    UtcRange,
    build_range_selection,
    candidate_event_files,
    iter_event_stream,
    parse_shard_bounds,
)
from .intervals import (
    MonoInterval,
    intersect_intervals,
    interval_rows,
    normalize_intervals,
    subtract_intervals,
    union_duration_ms,
)
from .statistics_v3 import (
    ComparisonConfig,
    WORKFLOW_STAGE_MAP,
    compare_ranges,
    episode_time_decomposition,
    time_contribution_metrics,
    workflow_stage_for_action,
    workflow_stage_metrics,
)
from .quality_gate import (
    RecordingGateThresholds,
    benchmark_callback,
    evaluate_recording_gate,
    validate_first_stage_configuration,
)
from .export_worker import (
    ExportCancellation,
    ExportCancelledError,
    ExportProgress,
    run_export_job,
)
from .streaming import StreamingAnalytics, stream_calculate_statistics
from .traces import (
    TraceCandidate,
    collect_trace_candidates,
    extract_trace_events,
    select_trace_candidates,
)
from .benchmark import (
    BenchmarkThresholds,
    benchmark_recording_callback,
    benchmark_stream,
    generate_events,
    write_fixture,
)
from .bundle import export_analysis_bundle
from .context import CONTEXT_VERSION, build_shape_context
from .metrics import (
    action_metrics,
    episode_cycle_metrics,
    episode_metrics,
    feature_comparisons,
    image_metrics,
    measurement_quality,
    object_metrics,
    rework_metrics,
    semantic_actions,
    repetition_diagnostics,
    sequence_metrics,
)
from .versions import (
    ACTION_SCHEMA_VERSION,
    BUNDLE_SCHEMA_VERSION,
    CONTEXT_SCHEMA_VERSION,
    EVENT_ENVELOPE_VERSION,
    PERCENTILE_RULE_VERSION,
    RECORDING_STORAGE_VERSION,
    REWORK_RULE_VERSION,
    STATISTICAL_EXPORT_VERSION,
    WORKFLOW_STAGE_VERSION,
    WORKFLOW_TIMELINE_VERSION,
    TIME_DECOMPOSITION_VERSION,
    SEQUENCE_RULE_VERSION,
    OBJECT_WORKFLOW_EXPORT_VERSION,
)
from .recorder import LocalEventRecorder, RecorderHealth
from .manifest import (
    ManifestDiagnostic,
    diagnose_event_shards,
    rebuild_event_shard_manifest,
)
from .retention import CleanupSummary, cleanup_event_logs
from .replay import replay_events
from .schema import (
    ANALYTICS_ALGORITHM_VERSION,
    EVENT_SCHEMA_VERSION,
    SUPPORTED_EVENT_SCHEMA_VERSIONS,
    EventEnvelope,
    EventResult,
    EventType,
    EventValidationError,
    EpisodeEndReason,
    InputSource,
    SelectionSource,
    UnattributedReason,
)
from .session import (
    ActivitySegment,
    ImageVisit,
    ObjectEpisode,
    ProjectSession,
    SessionTracker,
)
from .telemetry import BehaviorTelemetry
from .workflow import (
    DEFAULT_IDLE_BOUNDARY_MS,
    SUPPORTED_SHAPES,
    WORKFLOW_STAGES,
    WorkflowAction,
    WorkflowRecord,
    WorkflowTimeline,
    build_object_workflow_timeline,
    build_timeline,
    build_workflow_timeline,
    calculate_project_bottlenecks,
    decompose_workflow,
    object_workflow_summary,
    project_bottlenecks,
    sequence_metrics as workflow_sequence_metrics,
)

__all__ = [
    "ANALYTICS_ALGORITHM_VERSION",
    "EVENT_ENVELOPE_VERSION",
    "PERCENTILE_RULE_VERSION",
    "RECORDING_STORAGE_VERSION",
    "STATISTICAL_EXPORT_VERSION",
    "WORKFLOW_STAGE_VERSION",
    "WORKFLOW_TIMELINE_VERSION",
    "TIME_DECOMPOSITION_VERSION",
    "SEQUENCE_RULE_VERSION",
    "OBJECT_WORKFLOW_EXPORT_VERSION",
    "ACTION_CATALOG",
    "ACTION_CATALOG_VERSION",
    "ActionCatalogEntry",
    "action_catalog_to_dict",
    "validate_action_catalog",
    "ActivityTracker",
    "ActivityTransition",
    "ActivitySegment",
    "ActionSpanTracker",
    "CompletedAction",
    "compare_action_summaries",
    "BurstAggregator",
    "CompletedBurst",
    "AnalysisFilter",
    "ReadQuality",
    "UtcRange",
    "RangeSelection",
    "DualRangeSelection",
    "build_range_selection",
    "candidate_event_files",
    "iter_event_stream",
    "parse_shard_bounds",
    "MonoInterval",
    "normalize_intervals",
    "intersect_intervals",
    "subtract_intervals",
    "union_duration_ms",
    "interval_rows",
    "WORKFLOW_STAGE_MAP",
    "ComparisonConfig",
    "workflow_stage_for_action",
    "workflow_stage_metrics",
    "episode_time_decomposition",
    "time_contribution_metrics",
    "compare_ranges",
    "RecordingGateThresholds",
    "evaluate_recording_gate",
    "benchmark_callback",
    "validate_first_stage_configuration",
    "ExportCancellation",
    "ExportCancelledError",
    "ExportProgress",
    "run_export_job",
    "StreamingAnalytics",
    "stream_calculate_statistics",
    "TraceCandidate",
    "collect_trace_candidates",
    "extract_trace_events",
    "select_trace_candidates",
    "BenchmarkThresholds",
    "benchmark_recording_callback",
    "benchmark_stream",
    "generate_events",
    "write_fixture",
    "DEFAULT_FEATURE_KEYS",
    "EVENT_CATALOG",
    "EVENT_SCHEMA_VERSION",
    "SUPPORTED_EVENT_SCHEMA_VERSIONS",
    "EventDefinition",
    "EventEnvelope",
    "EventResult",
    "EventType",
    "EventValidationError",
    "EpisodeEndReason",
    "FeatureState",
    "FeatureDefinition",
    "FeatureRegistry",
    "FeatureStateTracker",
    "ClockReading",
    "BehaviorTelemetry",
    "DEFAULT_IDLE_BOUNDARY_MS",
    "SUPPORTED_SHAPES",
    "WORKFLOW_STAGES",
    "WorkflowAction",
    "WorkflowRecord",
    "WorkflowTimeline",
    "build_workflow_timeline",
    "build_object_workflow_timeline",
    "build_timeline",
    "decompose_workflow",
    "object_workflow_summary",
    "project_bottlenecks",
    "calculate_project_bottlenecks",
    "workflow_sequence_metrics",
    "IdentifierHasher",
    "ImageVisit",
    "InputSource",
    "SelectionSource",
    "UnattributedReason",
    "LocalEventRecorder",
    "ObjectEpisode",
    "ProjectSession",
    "SessionTracker",
    "SystemClock",
    "RecorderHealth",
    "CleanupSummary",
    "CONTEXT_VERSION",
    "build_shape_context",
    "ACTION_SCHEMA_VERSION",
    "BUNDLE_SCHEMA_VERSION",
    "CONTEXT_SCHEMA_VERSION",
    "REWORK_RULE_VERSION",
    "cleanup_event_logs",
    "replay_events",
    "new_session_id",
    "sanitize_payload",
    "calculate_statistics",
    "read_events",
    "action_metrics",
    "episode_cycle_metrics",
    "episode_metrics",
    "feature_comparisons",
    "image_metrics",
    "measurement_quality",
    "object_metrics",
    "rework_metrics",
    "semantic_actions",
    "repetition_diagnostics",
    "sequence_metrics",
    "export_analysis_bundle",
    "ManifestDiagnostic",
    "diagnose_event_shards",
    "rebuild_event_shard_manifest",
]
